import '../app/globals.css';
import { Funnel_Sans, Mona_Sans } from 'next/font/google';

// Load the fonts
const funnelSans = Funnel_Sans({
  subsets: ['latin'],
  variable: '--font-funnel-sans',
  weight: ['300', '400', '500', '600', '700', '800'], // Specify weights as an array
});

const monaSans = Mona_Sans({
  subsets: ['latin'],
  variable: '--font-mona-sans',
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'], // Specify weights as an array
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${funnelSans.variable} ${monaSans.variable}`}>
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body>
        {children}
        <div className="fixed inset-0 z-0 bg-dot-pattern bg-13px h-full w-full"></div>
        <div className="absolute inset-0 z-1 bg-gradient-to-b from-white to-transparent"></div>
      </body>
    </html>
  );
}